# Generated by Django 6.0.5 on 2026-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='afisha/%Y/%m/%d/', verbose_name='Фото для афишы')),
                ('date', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('is_free', models.BooleanField(default=False, verbose_name='Вход свободный?')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость за вход')),
                ('title', models.CharField()),
                ('description', models.TextField(verbose_name='Описание события')),
            ],
        ),
    ]
