# Generated by Django 6.0.5 on 2026-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posters',
            options={'verbose_name': 'Афиша', 'verbose_name_plural': 'Афишы'},
        ),
        migrations.AlterField(
            model_name='posters',
            name='price',
            field=models.CharField(blank=True, null=True, verbose_name='Стоимость за вход'),
        ),
    ]
