# Generated by Django 6.0.5 on 2026-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudish',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Категория'),
        ),
        migrations.RenameField(
            model_name='menudish',
            old_name='title',
            new_name='menu_title',
        ),
        migrations.AddField(
            model_name='menudish',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во (шт)'),
        ),
        migrations.AddField(
            model_name='menudish',
            name='menu_photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/%Y/%m/%d/', verbose_name='Фото для позиции в меню'),
        ),
        migrations.AddField(
            model_name='menudish',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='CategoryMenu',
        ),
    ]
