# Generated by Django 6.0.5 on 2026-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menudish_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudish',
            name='category',
            field=models.CharField(choices=[('hot', 'Горячее'), ('cold', 'Холодное'), ('drinks', 'Напитки')], max_length=200, verbose_name='Категория'),
        ),
    ]
